name: flutter_audio_query
description: Flutter plugin with null safe features to query data about artists, albums, songs, genres and playlists
  from device storage. based off of https://github.com/sc4v3ng3r/flutter_audio_query
version: 1.0.1+1
#author: Marcos Antonio Boaventura <scavenger.gnu@gmail.com>
homepage: https://github.com/amosogra/flutter_audio_query

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        package: boaventura.com.devel.br.flutteraudioquery
        pluginClass: FlutterAudioQueryPlugin